//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('ConversionTasks')
export class ConversionTasksEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  taskId: number;

  @Column('integer', { nullable: true })
  sourceFileId: number;

  @Column('integer', { nullable: true })
  targetFormat: number;

  @Column('text', { nullable: true })
  conversionStatus: string;

  @Column('date', { nullable: true })
  completionDate: Date;
}
