//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('ConversionFormats')
export class ConversionFormatsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  formatName: string;

  @Column('text', { nullable: true })
  formatType: string;

  @Column('text', { nullable: true })
  supportedFileTypes: string;
}
