//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const ConversionTasksTitle = () => {
  const record = useRecordContext();
  return <span>ConversionTasks {record ? `"${record.taskId}"` : ''}</span>;
};

export const ConversionTasksList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <NumberField source="taskId" />
      <ReferenceField source="sourceFileId" reference="UserFiles" />
      <ReferenceField source="targetFormat" reference="ConversionFormats" />
      <TextField source="conversionStatus" />
      <DateField source="completionDate" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const ConversionTasksEdit = () => (
  <Edit title={<ConversionTasksTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <NumberInput source="taskId" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="sourceFileId" reference="UserFiles" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="targetFormat" reference="ConversionFormats" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="conversionStatus" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="completionDate" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const ConversionTasksCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <NumberInput source="taskId" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="sourceFileId" reference="UserFiles" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="targetFormat" reference="ConversionFormats" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="conversionStatus" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="completionDate" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  <ReferenceInput
    source="sourceFileId"
    label="sourceFileId"
    reference="UserFiles"
    alwaysOn
  />,
  <ReferenceInput
    source="targetFormat"
    label="targetFormat"
    reference="ConversionFormats"
    alwaysOn
  />,
  ,
  ,
];
