//Source code generated by AppGPT (www.appgpt.tech)
import { Card, CardContent, CardHeader } from '@mui/material';
export const Dashboard = () => (
  <Card>
    <CardHeader title="I need an app developed that can seamlessly convert media and document files into different formats for user convenience and flexibility." />
    <CardContent>
      Develop a versatile app enabling users to effortlessly convert media and
      document files into various formats, enhancing accessibility and
      adaptability.
      <p>
        Built with{' '}
        <a
          href="https://www.appgpt.tech"
          target="_blank"
          rel="noopener noreferrer"
        >
          AppGPT
        </a>
      </p>
    </CardContent>
  </Card>
);
